apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-gateway
  namespace: ai-gateway-demo
  annotations:
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  rules:
    - host: ai-gateway.local
      http:
        paths:
          - path: /ai/summarize
            pathType: Prefix
            backend:
              service:
                name: ai-backend
                port:
                  number: 80
          - path: /ai/translate
            pathType: Prefix
            backend:
              service:
                name: ai-backend
                port:
                  number: 80
          - path: /ai/moderate
            pathType: Prefix
            backend:
              service:
                name: ai-backend
                port:
                  number: 80
